version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    assignees:
      - mustafagenc
    reviewers:
      - mustafagenc
    commit-message:
      prefix: deps
      prefix-development: deps(dev)
    groups:
      dependencies-major:
        update-types:
          - major
      dependencies-minor:
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: eslint
        versions: [">=9"]
      - dependency-name: jest
        versions: [">=30.0.0"]
      - dependency-name: "@types/jest"
        versions: [">=30.0.0"]